"""your message

Revision ID: 0ef72f85dc99
Revises: 2ad8bc262b73
Create Date: 2024-04-06 13:35:06.552695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef72f85dc99'
down_revision = '2ad8bc262b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
